name: flutter_html
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 4.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  # Plugin for parsing html
  html: ^0.15.3

  # Plugin for parsing css
  csslib: ^1.0.0

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.17.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2
  numerus:

  flutter_html_audio:
    path: packages/flutter_html_audio
  flutter_html_iframe:
    path: packages/flutter_html_iframe
  flutter_html_math:
    path: packages/flutter_html_math
  flutter_html_svg:
    path: packages/flutter_html_svg
  flutter_html_table:
    path: packages/flutter_html_table
  flutter_html_video:
    path: packages/flutter_html_video

dev_dependencies:
  flutter_lints: ^2.0.1
  meta: ^1.12.0
  melos: ^6.0.0

screenshots:
  - description: "An example of the output produced by flutter_html"
    path: example/screenshots/flutter_html_screenshot.png
  - description: "Continued example of the output produced by flutter_html"
    path: example/screenshots/flutter_html_screenshot1.png
  - description: "Continued example of the output produced by flutter_html"
    path: example/screenshots/flutter_html_screenshot2.png
  - description: "Continued example of the output produced by flutter_html"
    path: example/screenshots/flutter_html_screenshot3.png
  - description: "Another example of the output produced by flutter_html"
    path: example/screenshots/flutter_html_readme_screenshot.png

topics:
  - html
  - css
  - widgets
  - layout
  - flutter_html
