name: flutter_html_video
description: Video widget for flutter_html.
version: 4.0.0
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: ">=0.15.0 <1.0.0"

  flutter_html:
    git: https://github.com/JeanM1996/flutter_html.git

  video_player: ">=2.2.8 <3.0.0"
  chewie: ">=1.1.0 <2.0.0"

flutter:
