name: flutter_html_table
description: Table widget for flutter_html.
version: 4.0.0
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: ">=0.15.0 <1.0.0"
  flutter_html:
    path: ../..

  flutter_layout_grid: "2.0.6"

flutter:
